### ISSUE TITLE
The actual frequency is not consistent with the setting frequency.

### ISSUE THREAD

**Issue by jingedawang** [slightech/MYNT-EYE-S-SDK#14]
For example, when I set frequency to 55 in `mynteye.launch`:
```
<arg name="frame_rate" default="55" />
```
The actual frequency is only 39. Measured by `rostopic hz /mynteye/left/image_raw`:
```
average rate: 39.599
	min: 0.020s max: 0.031s std dev: 0.00258s window: 40
```

After a series of tests, I found that when setting frequency is equal or under 40, it is consistent with actual frequency. But when setting frequency is above 40, the actual frequency is always 40.

How to solve this problem?

Hardware configuration:
**Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz**
**4GB Memory**

**Comment by Osenberg-Q** [comment]
frame_rate and imu_rate need to be set simultaneously.
