### ISSUE TITLE
IMU paramters all zero

### ISSUE THREAD

**Issue by tiralonghipol** [slightech/MYNT-EYE-S-SDK#17]
Hi. I did the steps described in the guide, in particular when I execute:

> $ ./samples/_output/bin/tutorials/get_imu_params 

I get:
> I0907 17:17:28.220247 28268 utils.cc:26] Detecting MYNT EYE devices
I0907 17:17:28.369410 28268 utils.cc:36] MYNT EYE devices:
I0907 17:17:28.369446 28268 utils.cc:39]   index: 0, name: MYNT-EYE-S1030, sn: 4B4C212300090712
I0907 17:17:28.369454 28268 utils.cc:47] Only one MYNT EYE device, select index: 0
I0907 17:17:28.402329 28268 get_imu_params.cc:25] Motion intrinsics: {accel: {scale: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000], drift: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000], noise: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000], bias: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000]}, gyro: {scale: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000], drift: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000], noise: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000], bias: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000]}}
I0907 17:17:28.402410 28268 get_imu_params.cc:26] Motion extrinsics left to imu: {rotation: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000, 0.00000000000000000], translation: [0.00000000000000000, 0.00000000000000000, 0.00000000000000000]} <

Why are all these parameters set to zero? 
I could not find any documentation on this, hope you can help me 

Thanks!

**Comment by KalmanXiong** [comment]
%YAML:1.0
---
in_accel:
   scale: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
   drift: [ 0.0, 0.0, 0.0 ]
   noise: [ 0.016925432397973516, 0.016735310195561025, 0.017452487504590969 ]
   bias: [ 0.00019031356589714596, 0.00016996777864587261, 0.00054490537096493644 ]
in_gyro:
   scale: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
   drift: [ 0., 0., 0. ]
   noise: [ 0.0010848026158819934, 0.0012466367883501759, 0.0011003229919806443 ]
   bias: [ 0.000023404834136742844, 0.000023596771567764949, 0.000014970418056326829 ]
ex_left_to_imu:
   rotation: [ -0.0064662, -0.99994994, -0.00763565, 0.99997909, -0.00646566, -0.00009558, 0.0000462, -0.00763611, 0.99997084 ]
   translation: [ 0.00533646, -0.04302922, 0.02303124 ]

**Comment by tiralonghipol** [comment]
@KalmanXiong  thanks!
but what I wanted to know is _how_ to get this parameters :)
thank you again

**Comment by v01d** [comment]
same problem here. is the IMU supposed to come factory calibrated or is this expected to be solved by the user? from the docs it would appear it is calibrated. It is strange that there is the intrinsic/extrinsic camera calibration but not the IMU calibration.

**Comment by ClaudioCimarelli** [comment]
Why has this been closed without an answer? Are the params above valid for everyone? 
I purchased an S1030. Thank you.

**Comment by harjeb** [comment]
S1030 doesn't calibrate imu, so the imu params is vaild. Also you can use our default imu.params in samples/config/S1030.
