### ISSUE TITLE
Read device infos failed

### ISSUE THREAD

**Issue by Hunter-Duo** [slightech/MYNT-EYE-S-SDK#18]
Hi. I did the steps described in the guide, but when I execute:
./samples/_output/bin/api/camera_a
I get
I0921 18:42:33.445112 12866 utils.cc:26] Detecting MYNT EYE devices
W0921 18:42:33.788305 12866 uvc-v4l2.cc:241] xu_control_query failed error 2, No such file or directory
W0921 18:42:33.788388 12866 channels.cc:555] GetFiles failed
F0921 18:42:33.788406 12866 device.cc:546] Read device infos failed. Please upgrade your firmware to the latest version.
*** Check failure stack trace: ***
    @     0x7f3cd6edb95d  google::LogMessage::Fail()
    @     0x7f3cd6eddf74  google::LogMessage::SendToLog()
    @     0x7f3cd6edb3db  google::LogMessage::Flush()
    @     0x7f3cd6edecfe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3cd6eb5019  mynteye::Device::ReadAllInfos()
    @     0x7f3cd6eb55ab  mynteye::Device::Device()
    @     0x7f3cd6ebbec0  mynteye::StandardDevice::StandardDevice()
    @     0x7f3cd6eb3233  mynteye::Device::Create()
    @     0x7f3cd6eaf589  mynteye::Context::Context()
    @     0x7f3cd6eae889  mynteye::device::select()
    @     0x7f3cd6ebd333  mynteye::API::Create()
    @           0x402763  main
    @     0x7f3cd5099830  __libc_start_main
    @           0x404da9  _start
    @              (nil)  (unknown)

Why the program can not run normally？
I can't find the reason for this, hope you can help me

Thanks!

**Comment by joinAero** [comment]
Please upgrade your firmware to the latest version, see

* [Change from SDK 1.x to 2.x](https://slightech.github.io/MYNT-EYE-SDK-2-Guide/src/firmware/from_v1.html)
* [How to upgrade the firmware](https://slightech.github.io/MYNT-EYE-SDK-2-Guide/src/firmware/upgrade.html)
