### ISSUE TITLE
uvcvideo: Failed to query (GET_INFO) UVC control

### ISSUE THREAD

**Issue by tiralonghipol** [slightech/MYNT-EYE-S-SDK#19]
Hi.
I've been using the mynteye since a while now, and a new error pop up:

dmesg -w:

>[ 1798.637883] usb 2-1.6.1: USB disconnect, device number 13
[ 1804.616793] usb 1-1.4: new high-speed USB device number 7 using ehci-pci
[ 1804.727039] usb 1-1.4: New USB device found, idVendor=04b4, idProduct=00f8
[ 1804.727043] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1804.727045] usb 1-1.4: Product: MYNT-EYE-S1030
[ 1804.727048] usb 1-1.4: Manufacturer: MYNT
[ 1804.727050] usb 1-1.4: SerialNumber: 4B4C212300090712
[ 1804.727482] uvcvideo: Found UVC 1.00 device MYNT-EYE-S1030 (04b4:00f8)
[ 1804.744025] uvcvideo 1-1.4:1.0: Entity type for entity Extension 3 was not initialized!
[ 1804.744029] uvcvideo 1-1.4:1.0: Entity type for entity Processing 2 was not initialized!
[ 1804.744032] uvcvideo 1-1.4:1.0: Entity type for entity Camera 1 was not initialized!
[ 1804.744276] input: MYNT-EYE-S1030 as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.4/1-1.4:1.0/input/input15
[ 1826.583945] uvcvideo: Failed to query (GET_INFO) UVC control 4 on unit 3: -110 (exp. 1).<

So the camera is detected, but when I roslaunch the ros wrapper, I get this error

Can you please help me how to solve this problem? 
Thanks a lot !

**Comment by yangruixuan** [comment]
Hi @tiralonghipol What is your OS and hardware?
