### ISSUE TITLE
Cannot get quaternion data

### ISSUE THREAD

**Issue by Jing-lun** [slightech/MYNT-EYE-S-SDK#26]
**Hi all,
My problem is just like following: could only get the 6-axis data of imu but cannot directly get the quarternion data, any ideas?

---- when roslaunch start ----
W/uvc-v4l2.cc:245 xu_control_query failed error 5, Input/output error
W/channels.cc:939 XuCamCtrlGet value of Option::ACCELEROMETER_RANGE failed
W/uvc-v4l2.cc:245 xu_control_query failed error 5, Input/output error
W/channels.cc:939 XuCamCtrlGet value of Option::GYROSCOPE_RANGE failed

---- when rostopic echo start ----
header: 
  seq: 3495
  stamp: 
    secs: 1544135338
    nsecs: 610696316
  frame_id: "mynteye_imu_frame"
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.0138484376684
  y: 0.0154463343225
  z: -0.0103863282513
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: -0.992919921875
  y: 1.63054199219
  z: 9.93757324219
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---**

**Comment by KalmanXiong** [comment]
IMU data is raw data acquired from sensors. You should get quaternion by converting it from raw data
