### ISSUE TITLE
Issue while running samples downloaded from PPA

### ISSUE THREAD

**Issue by vishnukumarts** [slightech/MYNT-EYE-S-SDK#30]
Hi,

I am getting the below issue, while running the samples and most of the applications are crashed.
# ./get_all_device_info 
I/get_all_device_info.cc:23 Detecting MYNT EYE devices
W/uvc-v4l2.cc:245 xu_control_query failed error 5, Input/output error
W/uvc-v4l2.cc:539 xu_control_range query min failed
W/uvc-v4l2.cc:245 xu_control_query failed error 5, Input/output error
W/uvc-v4l2.cc:545 xu_control_range query max failed
W/uvc-v4l2.cc:245 xu_control_query failed error 5, Input/output error
W/uvc-v4l2.cc:551 xu_control_range query def failed
W/channels.cc:1045 Get XuControlInfo of Option::ACCELEROMETER_RANGE failed
W/uvc-v4l2.cc:245 xu_control_query failed error 5, Input/output error
W/uvc-v4l2.cc:539 xu_control_range query min failed
W/uvc-v4l2.cc:245 xu_control_query failed error 5, Input/output error
W/uvc-v4l2.cc:545 xu_control_range query max failed
W/uvc-v4l2.cc:245 xu_control_query failed error 5, Input/output error
W/uvc-v4l2.cc:551 xu_control_range query def failed
W/channels.cc:1045 Get XuControlInfo of Option::GYROSCOPE_RANGE failed

Thanks,

**Comment by KalmanXiong** [comment]
Are you running on a virtual machine? Does the port support usb3.0? Is the firmware version up to date?

**Comment by arjunskumar** [comment]
I'm getting the same issues with Jetson TX2, and connected with USB3.0.
