### ISSUE TITLE
Please use standard ROS temperature messages, not a custom "Temp.msg"

### ISSUE THREAD

**Issue by ibaranov-cp** [slightech/MYNT-EYE-S-SDK#32]
https://github.com/slightech/MYNT-EYE-S-SDK/blob/203c5ce18b45261d95a58092736769c757c29ace/wrappers/ros/src/mynt_eye_ros_wrapper/msg/Temp.msg#L1

There is a standard for this, which would enable display in RVIZ, re-use in other code, etc:
http://docs.ros.org/jade/api/sensor_msgs/html/msg/Temperature.html

**Comment by KalmanXiong** [comment]
We will fix the problem in the next version

**Comment by KalmanXiong** [comment]
I will notify you after the repair

**Comment by KalmanXiong** [comment]
Tag 2.3.0 fixed this issue
