### ISSUE TITLE
mynteye_right_frame tf frame incorrectly set (millimeters instead of meters)

### ISSUE THREAD

**Issue by ibaranov-cp** [slightech/MYNT-EYE-S-SDK#33]
mynteye_right_frame  tf_static has a value of 120.75; 0.35142; -0.97902
this seems to be accidental, tf values should be in meters, so it should be: 
0.12075; 0.00035142; −0.00097902

mynteye_imu_frame seems to be set correctly: 0.0053365; -0.043029; 0.023031

**Comment by KalmanXiong** [comment]
We will fix the problem in the next version

**Comment by KalmanXiong** [comment]
I will notify you after the repair

**Comment by KalmanXiong** [comment]
Tag 2.3.0 has  fixed this issue
