### ISSUE TITLE
MYNT-EYE ROS Wrapper Conversion Error

### ISSUE THREAD

**Issue by wsolichin-bto** [slightech/MYNT-EYE-S-SDK#34]
MYNT-EYE SDK on https://github.com/slightech/MYNT-EYE-S-SDK/tree/2.2.4 has a conversion error in camera_info topic. In ROS standard the conversion is m, but in the MYNT-EYE ROS wrapper the camera info projection matrix is in mm. Add after line 797 on https://github.com/slightech/MYNT-EYE-S-SDK/tree/2.2.4 in wrapper_nodelet.cc as follows:

```
camera_info->P.at(3) = camera_info->P.at(3)/ 1000.0;
```
and compile ROS again, this should correct camera info.

**Comment by v01d** [comment]
I also found this inconsistency. In fact, I was correcting the T variable, just before the stereoRectify() call, otherwise rectification transforms are incorrect.

**Comment by KalmanXiong** [comment]
We have fixed this issue on tags/2.3.1
