### ISSUE TITLE
Can't run SDK on windows 10

### ISSUE THREAD

**Issue by BrianTan34** [slightech/MYNT-EYE-S-SDK#37]
Hello I am following tutorial of SDK setup on windows 10.

https://slightech.github.io/MYNT-EYE-S-SDK-Guide/src/sdk/exe_install_windows.html

However when I run `get_stereo` and any other executable, the console shows 

`Detecting MYNT EYE devices` 

then quit.

However windows system notifies that it detected myntai device after SDK installation and system reboot.

Please advise, thank you!

**Comment by BrianTan34** [comment]
Thank you for your reply. Under VM windows 10. Port was selected as USB 3.0. I am using same machine (native OSX) running `uvc` sample, getting output.

I am also trying to understand the frame output. Is it stereo images overlaid together? Let me know if wants to open another issue.

<img width="750" alt="1" src="https://user-images.githubusercontent.com/12207821/52179499-4ea94200-2790-11e9-847f-9b6ec90f6fb6.png">

**Comment by BrianTan34** [comment]
Tried to do below request on OSX, however,  
```
 int main(int argc, char *argv[]) {
     glog_init _(argc, argv);

     auto &&device = device::select();
     if (!device) return 1;

     bool ok;
     auto &&request = device::select_request(device, &ok);
     if (!ok) return 1;
```
Then I encountered this error:

<img width="692" alt="screen shot 2019-02-03 at 12 06 07 pm" src="https://user-images.githubusercontent.com/12207821/52181932-78706200-27ac-11e9-84c2-00d8ea3a858d.png">

So I decide to update firmware under windows VM with latest 2.2.2 ver firmware

But encountered this error

<img width="1073" alt="screen shot 2019-02-03 at 12 10 31 pm" src="https://user-images.githubusercontent.com/12207821/52181959-c1c0b180-27ac-11e9-8095-7f7bed2c45f1.png">

**Comment by harjeb** [comment]
hi @BrianTan34 ，SDK in mac OS just support `uvc` now, please use Windows 10 or Ubuntu to get all the features(not support VM also)

**Comment by BrianTan34** [comment]
Thank you. Will close then.
