### ISSUE TITLE
Jetson TK1 crash when running camera_a

### ISSUE THREAD

**Issue by g-spacewhale** [slightech/MYNT-EYE-S-SDK#40]
I use a  MYNT-EYE-S1030 with the newest firmware. 
![image](https://user-images.githubusercontent.com/17550607/53181980-de584880-35f8-11e9-9b1f-c60d3ba44b63.png)

I installed this SDK on the Nvidia Jetson TK1; when running the camera_a  program, the TK1 freezes and then restarts after ~ 30 sec. Debugging the code, shows, that the program dies when calling ioctl() following the execution of this part of the _start_capture()_ function in uvc-v4l2.cc:

![image](https://user-images.githubusercontent.com/17550607/53182433-c7662600-35f9-11e9-91b7-9d2b0de5f0e7.png)

ioctl() returns -1 with an errno of 16 (device or resource busy). The previous value of errno after calling ioctl is 25 (Inappropriate ioctl for device).

The TK1 runs  Linux version 3.10.40-ga7da876 (buildbrain@mobile-u64-234) (gcc version 4.5.3 (crosstool-NG hg_unknown@20110628.165246) )

Connecting the MYNT EYE to a PC running ubuntu 14.04 and using this SDK to run camera_a worked with no problem. 

Can anyone explain, why this happens or/and assist in resolving this issue?
I will gladly supply any further necessary information about the setup.

best wishes

**Comment by g-spacewhale** [comment]
Solution:
The respective ioctl() call originating from the `_startup_capture()_` with the `request = 0x40045612` (in hex) is called twice by design, even if the first ioctl call returns no error:

the original code (lines 334 - 343 in vim uvc-v4l2.cc )

```

335     for (int i = 0; i < 10; ++i) {
336       if (xioctl(fd, VIDIOC_STREAMON, &type) < 0) {
337         std::this_thread::sleep_for(std::chrono::milliseconds(100));
338       }
339     }
340     if (xioctl(fd, VIDIOC_STREAMON, &type) < 0)
341       LOG_ERROR(FATAL, "VIDIOC_STREAMON");
342 
343     is_capturing = true;
```
This does not represent a problem on the i86 64 bit, the call returns 0 error on both occasions (call 336 and 340. 

The change I made in the code to allow for repeatable execution, calling the ioctl only once:

```
335     for (int i = 0; i < 10; ++i) {
336       if (xioctl(fd, VIDIOC_STREAMON, &type) < 0) {
337         std::this_thread::sleep_for(std::chrono::milliseconds(100));
338       }
339       else
340       {
341         is_capturing = true;
342         return;
343       }
344     }
```

Why is this not the default way of handling the call?

I don't know yet, why this repeated call not only breaks the program but breaks the entire kernel completely.

**Comment by joinAero** [comment]
Thanks, RD will ensure `xioctl VIDIOC_STREAMON` success only once in next version `2.3.4`.

**Comment by joinAero** [comment]
Pushed this fix to `develop` branch
