### ISSUE TITLE
2.3.0: Read device infos failed.

### ISSUE THREAD

**Issue by h4x0rz** [slightech/MYNT-EYE-S-SDK#42]
Upgraded firmware multiple times to 2.3.0 and updated SDK to 2.3.2 on Ubuntu 16.04 yet getting "Read device infos failed. Upgrade firmware" error messaged.
So I switched to windows and got the new Windows SDK and tried the samples - works perfectly!

Any errors with the 2.3.2 on Linux?
- MYNT device is detected, but xu_control_query and pu_control_range fails with error 25: Inappropriate ioctl for device.
- XuControlInfo fails for every component
- GetFiles fails

**Comment by harjeb** [comment]
hi,  pu(Processing Unit) and xu(Extension Unit）are used by UVC, These errors means usb/uvc driver not work well or usb poor contact.

**Comment by jameswalmsley** [comment]
Hi @h4x0rz I believe this is due to an incorrect kernel version in the newer versions of Ubuntu.
Essentially V4L2 has changed and now instead of a single /dev/video device, V4L creates 2 for each camera.

See if you can install kernel version 4.14 (4.15 is when V4L changed).

I'm trying to get this to work myself, I'll let you know if I succeed.

**Comment by jameswalmsley** [comment]
@harjeb See:: https://github.com/IntelRealSense/librealsense/issues/1514

Realsense had the same issue.

**Comment by jameswalmsley** [comment]
Works great:
See: https://wiki.ubuntu.com/Kernel/MainlineBuilds

Download:
https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.113/

* linux-image-unsigned-4.14.113-0414113-generic_4.14.113-0414113.201904200930_amd64.deb
* linux-modules-4.14.113-0414113-generic_4.14.113-0414113.201904200930_amd64.deb

    sudo dpkg -i *.deb

Then reboot into the correct kernel using the grub menu on reboot.
(Comment out GRUB_TIMEOUT=0 in /etc/default/grub and the run sudo update-grub before rebooting).

Hope this helps people get up and running for now.
@harjeb  @mynteye hope you are aware of this and how to solve it.

**Comment by harjeb** [comment]
@jameswalmsley Yes, looks like you are correct, thanks for reporting this,  @h4x0rz please use kernel version <=4.15, we'll solve this issue sooner.

**Comment by bergercookie** [comment]
Hey @harjeb,

Is this issue solved? If so could you point me to the branch/commit that I should be using to get this fix?

**Comment by harjeb** [comment]
@bergercookie hi, make sure firmware version is 2.4.0 ，and kernel version <= 4.15.  xu_control_query and pu_control_range errors related to USB or UVC driver, not SDK.  Please have a try on other USB ports or computers

**Comment by bergercookie** [comment]
I understand. It's just a bit confusing though closing the issue since there is no actual fix for kernel >= 4.15.

**Comment by agrathwohl** [comment]
Hey @bergercookie,

Do I understand correctly, that this issue makes the MYNT-EYE-S SDK unusable on any Linux whose kernel is >=4.15? Or is this just an issue with Ubuntu?

**Comment by bergercookie** [comment]
Hey @agrathwohl,

Correct.
