### ISSUE TITLE
MYNTEYE_BOX Download Link Empty File

### ISSUE THREAD

**Issue by wsolichin-bto** [slightech/MYNT-EYE-S-SDK#44]
So I want to upgrade my MYNT-EYE S Firmware to 2.x to use the SDK 2.x, and try to follow this link: https://slightech.github.io/MYNT-EYE-S-SDK-Guide/src/firmware/upgrade.html, but when I click on it and it finished downloading, the zip file is empty. It turns out in this GitHub page:http://doc.myntai.com/mynteye/s/download, there is also Firmware update but the file is also empty. Where can I find the correct firmware download link?

Thank you for your help.

**Comment by CeilingFANC** [comment]
You can try 7-zip to unzip the file.

**Comment by wsolichin-bto** [comment]
Thanks! 7-zip unzip the file properly, closing this issue.

**Comment by zldodo** [comment]
I also found the same issue, but have no idea to fix it.
Could you give me more hints about '7-zip to unzip the file.' What does 'the file' mean? Thanks a lot.
