### ISSUE TITLE
hard to soft time is wrong

### ISSUE THREAD

**Issue by v01d** [slightech/MYNT-EYE-S-SDK#53]
Last change (c279d97261a52770bb8353a68391076f6fbdd5ef) to this function introduced some problems. While some double math was converted, soft_time_begin was still a double. I've also fixed some typos and corrected uints (they were expressed as ns where they are actually us). Here's a corrected version:

<pre>
  ros::Time hardTimeToSoftTime(std::uint64_t _hard_time) {
    static bool isInited = false;
    static ros::Time soft_time_begin;
    static std::uint64_t hard_time_begin(0);

    if (false == isInited) {
      soft_time_begin = ros::Time::now();
      hard_time_begin = _hard_time;
      isInited = true;
    }

    std::uint64_t time_us_delta = (_hard_time - hard_time_begin);
    std::uint64_t time_us_delta_s = time_us_delta / 1000000;
    std::uint64_t time_us_delta_us = time_us_delta % 1000000;

    return soft_time_begin + ros::Duration(time_us_delta_s,
                                       time_us_delta_us * 1000);
  }
</pre>

In any case, I still get a negative delay for messages, meaning that soft to hard time mapping is not correct in absolute terms:

<pre>
v01d@kanji-i7:~/ros/src/thirdparty/MYNT-EYE-SDK-2/wrappers/ros/src/mynt_eye_ros_wrapper$ rostopic delay /mynteye/left/image_raw
subscribed to [/mynteye/left/image_raw]
average delay: -0.041
	min: -0.041s max: -0.041s std dev: 0.00013s window: 25
average delay: -0.041
	min: -0.041s max: -0.040s std dev: 0.00021s window: 50
^Caverage delay: -0.041
	min: -0.041s max: -0.040s std dev: 0.00022s window: 58
v01d@kanji-i7:~/ros/src/thirdparty/MYNT-EYE-SDK-2/wrappers/ros/src/mynt_eye_ros_wrapper$ rostopic delay /mynteye/imu/data_raw
subscribed to [/mynteye/imu/data_raw]
average delay: -0.026
	min: -0.050s max: 0.002s std dev: 0.01197s window: 194
average delay: -0.026
	min: -0.050s max: 0.004s std dev: 0.01207s window: 394
^Caverage delay: -0.026
	min: -0.050s max: 0.004s std dev: 0.01206s window: 448
</pre>

**Comment by joinAero** [comment]
[2.3.9](https://github.com/slightech/MYNT-EYE-S-SDK/tree/2.3.9) fixed the ros timestamp issue
