### ISSUE TITLE
POINT CLOUD, MYNT EYE S

### ISSUE THREAD

**Issue by logindiamant** [slightech/MYNT-EYE-S-SDK#55]
Dear collegues!

We want to get high quality point cloud from MYNT EYE S1030 cam, without empty undefined areas as shown below
Please, help us to solve problem

![Screenshot at 2019-07-16 18_56_03](https://user-images.githubusercontent.com/39023197/61319081-a87a6180-a830-11e9-887b-7ab629f690f1.png)
![Screenshot at 2019-07-16 18_56_23](https://user-images.githubusercontent.com/39023197/61319084-a87a6180-a830-11e9-86e5-02176a6c018d.png)
![Screenshot at 2019-07-16 19_03_24](https://user-images.githubusercontent.com/39023197/61319085-a912f800-a830-11e9-965e-74fd81586953.png)
![Screenshot from 2019-07-16 16-26-57](https://user-images.githubusercontent.com/39023197/61319086-a912f800-a830-11e9-8494-60d9980b96e0.png)

market picture
![s_color_points](https://user-images.githubusercontent.com/39023197/61319110-b92ad780-a830-11e9-8041-794e9c3082de.gif)

**Comment by harjeb** [comment]
Hi, there are two disparity computing method in SDK，default is bm and the market picture use sgbm. 
you can follow https://mynt-eye-s-sdk.readthedocs.io/en/latest/src/sdk/data/get_disparity.html to change. Or you can modify the config [file](https://github.com/slightech/MYNT-EYE-S-SDK/blob/master/wrappers/ros/src/mynt_eye_ros_wrapper/config/process/process_config.yaml) to use it in ROS

**Comment by logindiamant** [comment]
Thanks for your answer, harjeb!

I change algorithm to sgbm. Now we have a good point clouds!
![Screenshot from 2019-07-17 15-24-47](https://user-images.githubusercontent.com/39023197/61360421-99cf9100-a8a8-11e9-8794-8b63002153cf.png)
![Screenshot at 2019-07-17 14_47_25](https://user-images.githubusercontent.com/39023197/61360502-be2b6d80-a8a8-11e9-84b0-bcb2f4c5affc.png)
![Screenshot at 2019-07-17 14_48_37](https://user-images.githubusercontent.com/39023197/61360507-c2578b00-a8a8-11e9-9840-7b5551871fc9.png)

First question is, if I change
api->SetOptionValue(Option::IR_CONTROL, 160);
from infrared.cc, does this change saved in cam, and ready to apply in ros wraper?

Second question is, does MYNT EYE have methods to thin out a fake points?
Same as in RealSense
https://github.com/IntelRealSense/librealsense/blob/master/src/proc/decimation-filter.cpp

![Screenshot at 2019-07-17 15_15_16](https://user-images.githubusercontent.com/39023197/61361248-5e35c680-a8aa-11e9-989c-1d8cf4ff6656.png)
![Screenshot at 2019-07-17 15_15_29](https://user-images.githubusercontent.com/39023197/61361258-60982080-a8aa-11e9-95dc-9e8b4f41a353.png)

**Comment by harjeb** [comment]
Hi， For S1030 device you need modify this  [file](https://github.com/slightech/MYNT-EYE-S-SDK/blob/cdae311e99574516f151a5e96bd70faf26696326/wrappers/ros/src/mynt_eye_ros_wrapper/config/device/standard.yaml#L38) to change the IR strength. Here is document about use ros https://mynt-eye-s-sdk.readthedocs.io/en/latest/src/wrapper/ros.html#wrapper-ros.
And for now, we don't have methods to thin out a fake points

**Comment by logindiamant** [comment]
Thanks, harjeb
Please tel us, how to change/reduce resolution with sgbm?
Or other methods to speed up calculations. In Jetson TX2 we have only 3-4Hz point cloud
I try to change standard/request_index: 0 to 1 in standard.yaml, but device is crashed in ros

**Comment by harjeb** [comment]
Hi，this crash issue has fixed in develop branch, you can switch to this branch. And sgbm do spend much more resources than bm algorithm, and this is the config [file ](https://github.com/slightech/MYNT-EYE-S-SDK/blob/develop/config/disparity_config.yaml)

**Comment by logindiamant** [comment]
We have already speed up calculations to 30Hz in NUC BLKNUC7I7DNK2E
# standard/frame_rate range: {10,15,20,25,30,35,40,45,50,55,60}
standard/frame_rate: 30
# MYNTEYE-S1030, Reslution: 376x240, Format: YUYV
standard/request_index: 1
develop branch
Thanks, harjeb!

**Comment by logindiamant** [comment]
We plan to change our multi-cam RealSense platform to multi-cam MYNT EYE
Because we have a big problem, usb hub Orico destroy 4 RealSenses...

Please, tel us what usb hubs you recomended for plug in 2 and 4 MYNT EYE S1030
