### ISSUE TITLE
Settings for Outdoor drone ?

### ISSUE THREAD

**Issue by alter-sachin** [slightech/MYNT-EYE-S-SDK#68]
Hello!
I have been using the MYNT eye model S to use it for obstacle avoidance in outdoors conditions. 
The results have been not as I thought they would..

How do I adjust the settings to make this work well outdoors?

https://www.youtube.com/watch?v=_rDZf6phQ5w
The video above mentions : "The particular camera is calibrated for close range accuracy"

How do I achieve this ?

**Comment by jiziye** [comment]
Hello,
The camera used in the video is our D series camera, and the D1000-120 camera depth detection distance is 0.32-7m. The S1030 depth detection distance of 0.8-5m. The depth map of the D series will be better than the S1030. 
If your S1030 depth map is not good enough, we recommend that you recalibrate the camera. We already have calibration tools available.
https://mynt-eye-s-sdk.readthedocs.io/en/latest/src/tools/calibration_tool.html
