### ISSUE TITLE
Can‘t find the tools in MYNT-EYE-S-SDK

### ISSUE THREAD

**Issue by XiongLianga** [slightech/MYNT-EYE-S-SDK#71]
When I want to use the tools  to make dataset by myself,  I can't find the folder of tools.  And, I use the command "make tools",  this also gets a error. How can I get the tools in the MYNT-EYE-S-SDK? Thank you for your solution.

**Comment by harjeb** [comment]
Now tools are moved to `samples` folder.

**Comment by XiongLianga** [comment]
Thank you. I have found this right now.



发自我的iPhone


------------------ Original ------------------

**Comment by ClaudioCimarelli** [comment]
I cannot find the calibration tools under samples folder.  Where are the binaries? Thank you

**Comment by harjeb** [comment]
@ClaudioCimarelli Hi, calibration tool is not in SDK, you can follow https://mynt-eye-s-sdk.readthedocs.io/en/latest/src/tools/contents.html
