### ISSUE TITLE
在S1040上运行ROS Wrapper报错

### ISSUE THREAD

**Issue by luffycheung** [slightech/MYNT-EYE-S-SDK#94]
环境：树莓派4、opencv3.4.1、ros melodic；
samples sdk运行正常。
执行roslaunch mynt_eye_ros_wrapper mynteye.launch后报错如下
[mynteye/mynteye_wrapper_node-2] process has died [pid 1287, exit code -7, cmd /home/pi/Downloads/MYNT-EYE-S-SDK-master/wrappers/ros/devel/lib/mynt_eye_ros_wrapper/mynteye_wrapper_node __name:=mynteye_wrapper_node __log:=/home/pi/.ros/log/94e6e30e-847c-11ea-8375-dca6325f8ce7/mynteye-mynteye_wrapper_node-2.log].
log file: /home/pi/.ros/log/94e6e30e-847c-11ea-8375-dca6325f8ce7/mynteye-mynteye_wrapper_node-2*.log

**Comment by zhangjun-xyz** [comment]
How do you solve your problem?

**Comment by Z-Jeff** [comment]
出现了同样的问题，请问解决了吗

> 环境：树莓派4、opencv3.4.1、ros melodic； samples sdk运行正常。 执行roslaunch mynt_eye_ros_wrapper mynteye.launch后报错如下 [mynteye/mynteye_wrapper_node-2] process has died [pid 1287, exit code -7, cmd /home/pi/Downloads/MYNT-EYE-S-SDK-master/wrappers/ros/devel/lib/mynt_eye_ros_wrapper/mynteye_wrapper_node __name:=mynteye_wrapper_node __log:=/home/pi/.ros/log/94e6e30e-847c-11ea-8375-dca6325f8ce7/mynteye-mynteye_wrapper_node-2.log]. log file: /home/pi/.ros/log/94e6e30e-847c-11ea-8375-dca6325f8ce7/mynteye-mynteye_wrapper_node-2*.log

**Comment by flashYB426** [comment]
有人有解决方法吗？

**Comment by Rosa712** [comment]
遇到同样的问题
